"""initial migration

Revision ID: 954fed5ebacb
Revises: 
Create Date: 2026-01-06 16:44:53.525110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954fed5ebacb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customers',
    sa.Column('GivenName', sa.String(length=50), nullable=False),
    sa.Column('Surname', sa.String(length=50), nullable=False),
    sa.Column('Streetaddress', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('Zipcode', sa.String(length=10), nullable=False),
    sa.Column('Country', sa.String(length=30), nullable=False),
    sa.Column('CountryCode', sa.String(length=2), nullable=False),
    sa.Column('Birthday', sa.DateTime(), nullable=False),
    sa.Column('NationalId', sa.String(length=20), nullable=False),
    sa.Column('TelephoneCountryCode', sa.Integer(), nullable=False),
    sa.Column('Telephone', sa.String(length=20), nullable=False),
    sa.Column('EmailAddress', sa.String(length=50), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Customers'))
    )
    op.create_table('Accounts',
    sa.Column('AccountType', sa.Enum('PERSONAL', 'CHECKING', 'SAVINGS', name='accounttype'), server_default=sa.text("'PERSONAL'"), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customers.Id'], name=op.f('fk_Accounts_CustomerId_Customers')),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Accounts'))
    )
    op.create_table('Transactions',
    sa.Column('Type', sa.String(length=20), nullable=False),
    sa.Column('Operation', sa.String(length=50), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.Column('NewBalance', sa.Integer(), nullable=False),
    sa.Column('AccountId', sa.Integer(), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['AccountId'], ['Accounts.Id'], name=op.f('fk_Transactions_AccountId_Accounts')),
    sa.PrimaryKeyConstraint('Id', name=op.f('pk_Transactions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    op.drop_table('Accounts')
    op.drop_table('Customers')
    # ### end Alembic commands ###
